language: generic 
sudo: required

services: 
    - docker

before_install:
    - docker build -t lolzzzi/react-test -f ./frontend/Dockerfile.dev ./frontend

script:
    - docker run -e CI=true lolzzzi/react-test npm test

after_success:
    - docker build -t lolzzzi/front ./frontend
    - docker build -t lolzzzi/nginx ./nginx
    - docker build -t lolzzzi/server ./server
    - docker build -t lolzzzi/worker ./worker

# Login into docker cli

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take build images and push them to docker hub
    - docker push lolzzzi/front
    - docker push lolzzzi/nginx
    - docker push lolzzzi/server
    - docker push lolzzzi/worker
    